<?php 
	$user_id=$_SESSION['login_user'];
	$utype=$_SESSION['user_type']=$row['type']; 
	$sub=mysqli_query($connection,"SELECT * FROM user_profile WHERE type='$utype' and id='$user_id'")or die(mysqli_error($connection));
	$array=mysqli_fetch_array($sub);
	$sub_id=$array['user_id'];
 ?>
<div class="panel-body"></div>
<div class="col-lg-12">
<div class="panel-body">
    <!-- Nav tabs -->
    <?php if ($utype=='admin') {?>
    <ul class="nav nav-tabs">
      <li><?php echo "<a href='dashboard.php?page=enq_daily_plan'>";?> Today's Plan</a></li>
      <li><?php echo "<a href='dashboard.php?page=enq_tommorrow_plan'>";?> Tomorrow's Plan</a></li>
      <li class="active"><a href="#Pending" data-toggle="tab">Pending Enquiry</a></li>
    </ul>
    <?php }else{ ?>
     <ul class="nav nav-tabs">
      <li><?php echo "<a href='user_dashboard.php?page=enq_daily_plan'>";?> Today's Plan</a></li>
      <li><?php echo "<a href='user_dashboard.php?page=enq_tommorrow_plan'>";?> Tomorrow's Plan</a></li>
      <li class="active"><a href="#Pending" data-toggle="tab">Pending Enquiry</a></li>
    </ul>
    <?php } ?>
      
<div class="tab-pane fade in active" id="Pending">
<div class="panel-body"></div>  <h4>Schedule Pending</h4>
<table class="table table-striped table-bordered table-hover dataTable no-footer" id="example">
	<thead>
        <tr>
			<th>Date & Time</th>
			<th>Student Name</th>	
			<th>Email</th>
			<th>Mobile No</th>
			<th>Course</th>	
			<th>Generated By</th>
		  <th>Assign To</th>																
		</tr>
	 </thead>
      <tbody>
<?php
$cur_date=date("Y-m-d");
if($utype=='user')
{
$run = mysqli_query($connection,"SELECT Distinct(`student_id`), MAX(`sche_date`),`generated_by`,`sche_time`,`sche_type`,`user_id`,`sub_user_id` FROM generate_log where `status`='active' GROUP BY `student_id` HAVING   `user_id`='$user_id' and MAX(`sche_date`)<'$cur_date' ")or die(mysqli_error($connection));
}else
{
$run = mysqli_query($connection,"SELECT Distinct(`student_id`), MAX(`sche_date`),`generated_by`,`sche_time`,`sche_type`,`user_id`,`sub_user_id` FROM generate_log where `status`='active' GROUP BY  `student_id` HAVING  `user_id`='$user_id' and MAX(`sche_date`)<'$cur_date' ")or die(mysqli_error($connection));
}
//$count=0;
	while($row = mysqli_fetch_array($run))
	{
		
		// $generated_by=$row['generated_by'];
		$sche_date=$row['MAX(`sche_date`)'];	
		$sche_time=$row['sche_time'];
	$timestamp1= strtotime($sche_date);
     	$date1=date('d-m-Y',$timestamp1);
     	$datetime=$date1.' '.' '.$sche_time;	
		$sche_type=$row['sche_type'];		
		$student_id=$row['student_id'];		
		//$count++;
		$var6=mysqli_query($connection,"select * from student where id='$student_id'");
		$row6=mysqli_fetch_array($var6);
		$ud=$row6['user_id'];
		$sud=$row6['sub_user_id'];
		$gen=$row6['generated_by'];
		$assign_to_name=$row6['assign_to_name'];
		$student_name=$row6['name'];
		$email=$row6['email'];
		if ($sud!=0) 
		{
		 	$sql = mysqli_query($connection,"SELECT * FROM user a INNER JOIN user_profile b on a.id=b.user_id where b.id='$gen'");
			$arr=mysqli_fetch_array($sql);
			$g_name=$arr['name'];
		}
		else{
			$sql = mysqli_query($connection,"SELECT * FROM user where id='$gen'");
			$arr=mysqli_fetch_array($sql);
			$g_name=$arr['name'];
		}
		
?>
		<tr>	
			<td><?php echo $datetime; ?></td>
			<td>
			<?php if ($utype=='admin'){ ?>
			<a href='dashboard.php?page=enquiry_plan&ed=<?php echo $student_id ?>'><?php echo $student_name; ?></a>
			<?php } else{?>
			<a href='user_dashboard.php?page=enquiry_plan&ed=<?php echo $student_id ?>'><?php echo $student_name; ?></a>
			<?php } ?>
			</td>
			<td><?php echo $email; ?></td>
			<td><?php echo $row6['contact_no']; ?></td>
			<td> <?php echo $row6['course_list']; ?></td>
			<td> <?php echo $g_name; ?></td>
			<td> <?php echo $assign_to_name; ?></td>

			


		</tr>
	<?php } ?>

			</tbody>
	</table>

</div>                                            

                      