<?php 
include('config.php');
			$user_id=$_SESSION['login_user'];
			$utype=$_SESSION['user_type']=$row['type']; 
			$sub=mysqli_query($connection,"SELECT * FROM user_profile WHERE type='$utype' and id='$user_id'")or die(mysqli_error($connection));
			$array=mysqli_fetch_array($sub);
			$sub_id=$array['user_id'];
?><div class="row">
<h3>Enquiry List
<?php 
	  	if($utype=='admin')
		{
	   ?>
	 <a  href='dashboard.php?page=new_enquiry' style="float:right;"> + New Enquiry</a></h3><hr>
	  <?php 
	 	 }
	 	 else
	 	 {
	   ?>
	   <a  href='user_dashboard.php?page=new_enquiry' style="float:right;"> + New Enquiry</a></h3><hr>
	<?php } ?>
	<div class="col-lg-12" id="filter"> 
	<div class="col-md-2">

		<select class="form-control" name="type" id="type" >
			<option value="" >Councellar Name</option>
			<?php
			$mode_qu=mysqli_query($connection,"SELECT * FROM user_profile where user_id='$user_id'")or die(mysqli_error($connection));
			while($row=mysqli_fetch_array($mode_qu))
			{
            ?>
			<option value="<?php echo $row['id'];?>"><?php echo $row['name'];?></option>
	<?php	
      }
	?>
			<!-- <option value="Recurring">Recurring Invoices</option> -->
			
		</select>
		<p id="msg"></p>
	</div>
	<div class="col-md-2">

		<select class="form-control" name="type1" id="type1" >
			<option value="" >Select one</option>
			<?php
			$mode_qu1=mysqli_query($connection,"SELECT * FROM mstr_schedule where user_id='$user_id' ")or die(mysqli_error($connection));
			while($row=mysqli_fetch_array($mode_qu1))
			{
            ?>
			<option value="<?php echo $row['id'];?>"><?php echo $row['sche_type'];?></option>
	<?php	
      }
	?>
		</select>
		<p id="msg"></p>
	</div>
   <input type="hidden" name="us_id" id="us_id" value="<?php echo $user_id; ?>">
   
	<div class="col-md-1">
		<label>From Date:-</label>
	</div>
	<div class="col-md-2">
		<input type="date" class="form-control" name="fromDate" id="fromDate" >
	</div>
	
	<div class="col-md-1">
		<label>To Date:-</label>
	</div>
	<div class="col-md-2">
		<input type="date" class="form-control" name="toDate" id="toDate" onclick="check()">
		<p id="msg1"></p>
	</div>
	
    <div class="col-md-1">
		<button name="search" id="search" type="submit" class="btn btn-primary">Search&nbsp;<span class="glyphicon glyphicon-search"></span></button>
	</div>
	
	<!-- <div class="col-md-1">
		<button type="reset" class="btn btn-danger" value="Reset" onclick="reset()">Reset</button>
	</div>
	 -->
</div>
	
<div class="col-md-12" id="reportdata">
  <h4>Recent Enquiry</h4>

    <table class="table table-striped table-bordered table-hover dataTable no-footer" id="example">
      <thead>
        <tr bgcolor="#999999">
          <th>Id</th>          
          <th>Date</th>
          <th>Student Name</th>          
          <th>Email Id</th>
          <th>Phone Number</th>		 
		  <th>Course List</th>
          <th>Fees</th>
          <th>Generated By</th>
		  <th>Assign To</th>
		  
          <th>Edit</th>
        </tr>
        </thead>
        <tbody>
		<?php		
		if($utype=='user')
		{	$qry=mysqli_query($connection,"SELECT * FROM student where status='active' ORDER BY `id` DESC")or die(mysqli_error($connection));

			}else{
				$qry=mysqli_query($connection,"SELECT * FROM student where status='active' ORDER BY `id` DESC")or die(mysqli_error($connection));

			}
					$cnt=1;
					while($row=mysqli_fetch_array($qry)){
					$c_id=$row['id'];
					$assign_to=$row['assign_to'];
					$generated_by=$row['generated_by'];
					$sud=$row['sub_user_id'];

		?>
		        <tr><td><?php echo $row['id'];?></td>
		        <td><?php echo date('d-m-Y', strtotime($row['cur_date']));?></td>
		            <td>
		            <?php if ($utype=='admin'){?>
		            <?php echo"<a href='dashboard.php?page=enquiry_plan&ed=".$row['id']."'>".$row['name']."</a>";?>
   					<?php }
   					else{ ?>
   					 <?php echo"<a href='dashboard.php?page=enquiry_plan&ed=".$row['id']."'>".$row['name']."</a>";?>
   					<?php } ?>
		            </td>
					<td><?php echo $row['email'];?></td>
					<td><?php echo $row['contact_no'];?></td>
					<td><?php echo $row['course_list'];?></td>
					<td><?php echo $row['course_fee'];?></td>
					<?php 
					if ($sud!=0) 
			{
			 	$sql = mysqli_query($connection,"SELECT * FROM user_profile where id='$generated_by'");
				$arr=mysqli_fetch_array($sql);
				$g_name=$arr['name'];
			}
			else{
				$sql = mysqli_query($connection,"SELECT * FROM user where id='$generated_by'");
				$arr=mysqli_fetch_array($sql);
				$g_name=$arr['name'];
			}

					?>

					<td><?php echo $g_name;?></td>
				
		          	<td><?php echo $row['assign_to_name'];?></td>
		          	
				    	
					
		         	<td>
		         	 <?php if ($utype=='admin'){?>
		           <?php echo "<a href='dashboard.php?page=new_enquiry&ed=".$row['id']."'>";?><span class="icon fa fa-edit"></span></a>
   					<?php }
   					else{ ?>
   					 <?php echo "<a href='dashboard.php?page=new_enquiry&ed=".$row['id']."'>";?><span class="icon fa fa-edit"></span></a>
   					<?php } ?>
		         	</td>
		        </tr>
		   <?php } ?>
        </tbody>
      </table>
    </div>
</div>
</div>

<script>
	function check()
	{
		var toDate=$('#toDate').val();
		if(toDate!=="mm/dd/yyyy")
		   {
			  $('#toDate').css('borderColor','#ccc');
			  $('#msg1').html('');		  
			}
	}
</script>

<script>
$('#search').click(function()
	{
		var fromDate=$('#fromDate').val();
		var toDate=$('#toDate').val();
		var us_id =$('#us_id').val();
		var type =$('#type').val();
		var type1 =$('#type1').val();
		

		    $.ajax({	
			  
					    url:'invoice_filter6.php',
					    type:'POST',
					    data:{
						        fromDate:fromDate,
						        toDate:toDate,
						        us_id:us_id,
						        type:type,
						        type1:type1
						        
					    },
					    success:function(data)
					    {
					      // alert(data);
					      $('#reportdata').html('');
					      $('#reportdata').html(data);

					      $('#example').DataTable({

							     "dom": 'lBfrtip',
							     "buttons": [
							            {
							                extend: 'collection',
							                text: 'Export',
							                exportOptions: {
							                   columns: [ 0, 1, 2]
							                    
							                },
							                buttons: [
							                    // 'copy',
							                    'excel'
							                    // 'csv',
							                    // 'pdf',
							                    // 'print'
							                ]
							            }
							        ]
							  });
	      
						      var table=$('#example').DataTable();
							      table
							      .order([[0,'desc']])
							      .draw(false);
					    }
					});

	});
</script>

<script type="text/javascript">
    var datefield=document.createElement("input")
    datefield.setAttribute("type", "date")
    if (datefield.type!="date"){ //if browser doesn't support input type="date", load files for jQuery UI Date Picker
        document.write('<link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/base/jquery-ui.css" rel="stylesheet" type="text/css" />\n')
        document.write('<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.4/jquery.min.js"><\/script>\n')
        document.write('<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js"><\/script>\n') 
    }
</script>
    <script>
if (datefield.type!="date"){ //if browser doesn't support input type="date", initialize date picker widget:
    jQuery(function($){ //on document.ready
        $('#fromDate').datepicker();
        $('#toDate').datepicker();
    })
}
</script>

