<h3 class="page-header">Enquiry Log </h3>
<h4>Client Information </h4>
<div class="col-lg-12">
<?php

	 $user_id=$_SESSION['login_user'];
	$utype=$_SESSION['user_type']=$row['type']; 
	$sub=mysqli_query($connection,"SELECT * FROM user_profile WHERE type='user' and id='$user_id'")or die(mysqli_error($connection));
	$array=mysqli_fetch_array($sub);
	 $sub_id=$array['user_id'];
	 $d_name=$array['department_id'];

	if(isset($_GET['ed']) && !empty($_GET['ed']))
		{
			$id=$_GET['ed'];
			$run1 = mysqli_query($connection,"SELECT * FROM student where id='$id'");	
			while($row1=mysqli_fetch_array($run1))
			{
				$id1=$row1['id'];
					$ud=$row1['user_id'];
						$sud=$row1['sub_user_id'];
				$name=$row1['name'];
				$assign_to=$row1['assign_to'];
				$source_type=$row1['source_type'];
					$assign_to_name=$row1['assign_to_name'];
				$course=$row1['course_list'];
				$email=$row1['email'];
				$contact_no=$row1['contact_no'];
				$course_fee=$row1['course_fee'];
				$generated=$row1['generated_by'];
				$run2 =mysqli_query($connection,"SELECT * FROM generate_log where student_id='$id'");

				$row2=mysqli_fetch_array($run2);

			}
		}
		if(isset($_GET['id']) && !empty($_GET['id']))
		{
			$id12=$_GET['id'];
			$run_update1 = mysqli_query($connection,"SELECT * FROM generate_log where id='$id12'");	
			while($row_update=mysqli_fetch_array($run_update1))
			{
			
           $up_comment=$row_update['en_remark'];
           $up_id=$row_update['id'];
           $sche_type=$row_update['sche_type'];
			}
			$run_update2 = mysqli_query($connection,"SELECT a.sche_type as bb FROM mstr_schedule a INNER JOIN generate_log b ON b.sche_type=a.id where b.id='$id12'");	$row_update1=mysqli_fetch_array($run_update2);
			      $dd1=$row_update1['bb'];
		}
?>
	<div class="col-md-6"><div class="col-md-4"><label>Student Name:</label></div><div class="col-md-8"><?php echo $name; ?></div></div>
	<div class="col-md-6"><div class="col-md-4"><label>Phone No:</label></div><div class="col-md-8"><?php echo $contact_no; ?></div></div>
	<div class="panel-body"></div>
	<div class="col-md-6"><div class="col-md-4"><label>Email-ID:</label></div><div class="col-md-8"><?php echo $email; ?></div></div>
	<div class="col-md-6"><div class="col-md-4"><label>Course List:</label></div><div class="col-md-8"><?php echo $course; ?></div></div>
	<div class="panel-body"></div>
	<div class="col-md-6"><div class="col-md-4"><label>Course Fees:</label></div><div class="col-md-8"><?php echo $course_fee; ?></div></div>
	<?php 
	if ($ud!=0 && $sud!=0) 
					{
					 	$sql = mysqli_query($connection,"SELECT * FROM user_profile where id='$generated'");
						$arr=mysqli_fetch_array($sql);
						$ge=$arr['name'];
					}
					else{
						$sql = mysqli_query($connection,"SELECT * FROM user where id='$generated'");
						$arr=mysqli_fetch_array($sql);
						$ge=$arr['name'];
					}
					
	
	?>
		<div class="col-md-6"><div class="col-md-4"><label>Generated By:</label></div><div class="col-md-8"><?php echo $ge; ?></div></div>
	<div class="panel-body"></div>
		<div class="col-md-6"><div class="col-md-4"><label>Lead Source:</label></div><div class="col-md-8"><?php echo $source_type; ?></div></div>
	<div class="col-md-6"><div class="col-md-4"><label>Assign To:</label></div><div class="col-md-8"><?php echo $assign_to_name; ?></div></div>
	

</div>	
<div class="panel-body"></div>

<div class="panel panel-primary">
    <div class="panel-heading">
      <b>Add Log</b><label style="margin-left:695px;">Date:&nbsp;&nbsp;<?php echo date("y/m/d"); ?></label>
	</div>
	
          <div class="panel-body">
              
             <form role="form" id="frm_student" name="frm_student" autocomplete="on" action="" method="POST" enctype="multipart/form-data">
	         
				<?php if(!isset($_GET['id']) && empty($_GET['id']))
				{
				?>	
			<div class="col-sm-6">
			<div class="form-group">
			<label>Select Status </label>
			<input type="hidden" name="sess_id11" class="form-control" value="<?php echo $user_id;?>">
			<input type="hidden" name="sub_us_id" value="<?php echo $sub_id; ?>">
			<input type="hidden" name="sub_us_ty" value="<?php echo $utype; ?>">
                        <input type="hidden" name="ed" value="<?php echo $id; ?>">
                        
                 
			<select name="sche_type" id="sche_type" class="form-control" required >
			<option value="">Select One </option>
                            <?php
				$qry5=mysqli_query($connection,"SELECT * FROM `mstr_schedule`");
					while($row5=mysqli_fetch_array($qry5))
					{
			?>
			<option value="<?php echo $row5['id'];?>"><?php echo $row5['sche_type'];?></option>
			<?php 		} ?>
                            
                            
                    
			</select>
			</div>			
			</div>
			<div class="col-sm-6">	
			<div class="form-group">
			<label for="Contact Name">Comment</label>
			<textarea name="en_remark" class="form-control" id="en_remark" required></textarea></div>
			</div>
			<div class="col-md-12" align="center">
			<button type="submit" name="submit" class="btn btn-md btn-primary "  id="btn_log" value="save" style="margin-left:5px;" onclick="document.pressed=this.value"><font size="" >Add</font></button>
			</div>	
		<?php }
		else
			{
				?>
<div class="col-sm-6">
			<div class="form-group">
			<label>Select Status </label>
			<input type="hidden" name="sess_id11" class="form-control" value="<?php echo $user_id;?>">
			<input type="hidden" name="sub_us_id" value="<?php echo $sub_id; ?>">
			<input type="hidden" name="sub_us_ty" value="<?php echo $utype; ?>">
                        <input type="hidden" name="ed" value="<?php echo $id; ?>">

                 
			<select name="sche_type" id="sche_type" class="form-control" required >
			<option value="<?php echo  $sche_type;?>"><?php echo $dd1;?></option>
                            <?php
				$qry5=mysqli_query($connection,"SELECT * FROM `mstr_schedule`");
					while($row5=mysqli_fetch_array($qry5))
					{
			?>
			<option value="<?php echo $row5['id'];?>"><?php echo $row5['sche_type'];?></option>
			<?php 		} ?>
                            
                            
                    
			</select>
			</div>			
			</div>
			<div class="col-sm-6">	
			<div class="form-group">
			<label for="Contact Name">Comment</label>
			<textarea name="en_remark" class="form-control" id="en_remark" required><?php echo $up_comment;?></textarea></div>
			</div>
			<div class="col-md-12" align="center">
			<button name="update" class="btn btn-md btn-primary" id="<?php echo $id12;?>"  style="margin-left:5px;" onclick="updateData(this)"><font size="" >Update</font></button>
			</div>	

			<?php }?>
			 
			<!-- <div class="panel-body"></div>
			<div class="col-sm-4">
			<div class="form-group">
			<label>Action</label>
			<select  name="en_status" class="form-control" >
			<option value="">Select Action </option>
                            <?php
				$qry5=mysqli_query($connection,"SELECT * FROM `action`");
					while($row5=mysqli_fetch_array($qry5))
					{
			?>
			<option value="<?php echo $row5['action'];?>"><?php echo $row5['action'];?></option>
			<?php 		} ?>
                            
                            
                    
			</select>
			</div></div>
			<div class="col-sm-4">
			<div class="form-group">	   
			<label for="Contact Name">Action Date</label>
			<input type="date" class="form-control" id="sche_date" name="sche_date"  placeholder="Schedule Date" required>
			</div>
			</div> 
			<div class="col-sm-4">
			<div class="form-group">
			<label for="Contact Name">Action Time</label>
	
			<input type="time" id='sche_time' name="sche_time"  class="form-control">												
			</div>
			</div>		 -->
					
						             
					
                       
			</form>
			</div>   
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script>
          
      
 $('form#frm_student').submit(function(e){

             e.preventDefault();

            if(document.pressed == 'save')
             {
                     $("button#btn_log").button('loading');
                     $.ajax({
						data:$("#frm_student").serialize(),
						type:"POST",
						url:'insert_log.php',

                    				success: function(data)
						{
							$("button#btn_log").button('reset');
//							  alert(data);
							 
						if(data==1)
							{
								// alert('Save Successfully !!!');
								
								//  window.location.href= "logproduct.php";
								  swal({
									  position: 'top-right',
                                                                          type: 'success',
	  								  title: 'Save Successfully!!!',
	  								  showConfirmButton: false,
	  								  timer: 1500
								  })
								  window.setTimeout(function()
								    { 
 										window.location.href= "dashboard.php?page=enquiry_plan&ed=<?php echo $id;?>";
 								 	} ,1500);
								 
							}
                                                        
                                                        
                                                       else if(data==3)
							{
								// alert('Save Successfully !!!');
								
								//  window.location.href= "logproduct.php";
								  swal({
									  position: 'top-right',
                                                                          type: 'success',
	  								  title: 'Save Successfully!!!',
	  								  showConfirmButton: false,
	  								  timer: 1500
								  })
								  window.setTimeout(function()
								    { 
 										window.location.href= "dashboard.php?page=enquiry_plan&ed=<?php echo $id;?>";
 								 	} ,1500);
								 
							}
							else if(data==2)
							{
								alert('Error....');
								// $('#msg').html('Please Check Error.');
								// $('#msg').css('color','red');
								return false;
							}
							
						}					 
					 });
	}else{
        
        
        	return true;
        
        }
    
    });
        </script>
    
    
</div>	
    <div class="panel panel-primary">
    <div class="panel-heading">Log Details</div>
    <div class="panel-body" style="overflow-y: scroll; overflow-x: scroll;">
	<table class="datatable table table-striped" id="example"  cellspacing="0" width="100%">
   <thead>
    <tr bgcolor="#999999">
	
	<td>Student Name</td>
	<td>Log Generated By</td>
    <!-- <td>Status</td>	 -->
     <td>Comment</td>
      <td>Edit</td>		            
      
        
	
    </tr>
	</thead>
    <tbody>
	<?php
	if(isset($_GET['ed']) && !empty($_GET['ed']))
	{
		 $id=$_GET['ed'];
			
			$run=mysqli_query($connection,"SELECT * FROM generate_log where student_id='$id' ORDER BY `id` DESC")or die(mysqli_error($connection));
	$count=0;
	while($row = mysqli_fetch_array($run))
	{
            $count++;	
		$tab_id=$row['id'];
		$cur_date=$row['cur_date'];
		$cur_time=$row['cur_time'];
		$sche_type=$row['sche_type'];
		$sche_date=$row['sche_date'];	
		//$sche_action=$row['sche_action'];		
		$sche_time=$row['sche_time'];
		//$en_call_type=$row['en_call_type'];	
		$en_status=$row['en_status'];
		$en_remark=$row['en_remark'];
		$dir_remark=$row['dir_remark'];
		$generated_by=$row['generated_by'];
	    $sud=$row['sub_user_id'];	
	    $student_id=$row['student_id'];
	    
	    	$timestamp = strtotime($cur_date);
     		$timestamp1= strtotime($sche_date);
     		$date1=date('d-m-Y',$timestamp);
     		$date2=date('d-m-Y',$timestamp1);
			  			
		$var5=mysqli_query($connection,"select * from admin_enquiry_status where enquiry_status_id='$en_status'");
		$row5=mysqli_fetch_array($var5);
		$var6=mysqli_query($connection,"select * from  mstr_schedule where id='$sche_type'");
		$row6=mysqli_fetch_array($var6);
		if(function_exists('date_default_timezone_set'))
		      {
                         date_default_timezone_set("Asia/Kolkata");
              }
 $data21=date('Y-m-d');
 $data222=date('h:i:s');
 $diff=strtotime($data21)-strtotime($cur_date);
 $diff1=strtotime($data222)-strtotime($cur_time);
 $tdiff= abs($diff1)/(60);
 $t_diff=bcdiv($tdiff,1,0);
 $days=$diff/(86400);
  if($days==0)
  {
  	if($t_diff<60)
  	{
  	?>
  	<td><b><?php echo "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;".$name."<br>";?></b><h6 style="position: relative;left:18px;"><?php echo $t_diff."&nbsp";?>Minutes Ago</h6></td>
  	<?php
  }
  else if($t_diff>=60 && $t_diff<120)
  {
  	?>
  	<td><b><?php echo "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;".$name."<br>";?></b><h6 style="position: relative;left:18px;">1 Hours Ago</h6></td>
  	<?php
  }
  else if($t_diff>=120 && $t_diff<180)
  {
  	?>
  	<td><b><?php echo "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;".$name."<br>";?></b><h6 style="position: relative;left:18px;">2 Hours Ago</h6></td>
  	<?php
  }
  else if($t_diff>=180 && $t_diff<240)
  {
  	?>
  	<td><b><?php echo "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;".$name."<br>";?></b><h6 style="position: relative;left:18px;">3 Hours Ago</h6></td>
  	<?php
  }
  else if($t_diff>=240 && $t_diff<300)
  {
  	?>
  	<td><b><?php echo "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;".$name."<br>";?></b><h6 style="position: relative;left:18px;">4 Hours Ago</h6></td>
  	<?php
  }
  else if($t_diff>=300 && $t_diff<360)
  {
  	?>
  	<td><b><?php echo "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;".$name."<br>";?></b><h6 style="position: relative;left:18px;">5 Hours Ago</h6></td>
  	<?php
  }
  else if($t_diff>=360 && $t_diff<420)
  {
  	?>
  	<td><b><?php echo "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;".$name."<br>";?></b><h6 style="position: relative;left:18px;">6 Hours Ago</h6></td>
  	<?php
  }
  else if($t_diff>=420 && $t_diff<480)
  {
  	?>
  	<td><b><?php echo "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;".$name."<br>";?></b><h6 style="position: relative;left:18px;">7 Hours Ago</h6></td>
  	<?php
  }
   else if($t_diff>=480 && $t_diff<540)
  {
  	?>
  	<td><b><?php echo "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;".$name."<br>";?></b><h6 style="position: relative;left:18px;">8 Hours Ago</h6></td>
  	<?php
  }
  else if($t_diff>=540 && $t_diff<600)
  {
  	?>
  	<td><b><?php echo "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;".$name."<br>";?></b><h6 style="position: relative;left:18px;">9 Hours Ago</h6></td>
  	<?php
  }
  else if($t_diff>=600 && $t_diff<660)
  {
  	?>
  	<td><b><?php echo "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;".$name."<br>";?></b><h6 style="position: relative;left:18px;">10 Hours Ago</h6></td>
  	<?php
  }
   else if($t_diff>=660 && $t_diff<720)
  {
  	?>
  	<td><b><?php echo "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;".$name."<br>";?></b><h6 style="position: relative;left:18px;">11 Hours Ago</h6></td>
  	<?php
  }
   else if($t_diff>=720 && $t_diff<780)
  {
  	?>
  	<td><b><?php echo "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;".$name."<br>";?></b><h6 style="position: relative;left:18px;">12 Hours Ago</h6></td>
  	<?php
  }
   else if($t_diff>=780 && $t_diff<840)
  {
  	?>
  	<td><b><?php echo "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;".$name."<br>";?></b><h6 style="position: relative;left:18px;">13 Hours Ago</h6></td>
  	<?php
  }
   else if($t_diff>=840 && $t_diff<900)
  {
  	?>
  	<td><b><?php echo "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;".$name."<br>";?></b><h6 style="position: relative;left:18px;">14 Hours Ago</h6></td>
  	<?php
  }
   else if($t_diff>=900 && $t_diff<960)
  {
  	?>
  	<td><b><?php echo "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;".$name."<br>";?></b><h6 style="position: relative;left:18px;">15 Hours Ago</h6></td>
  	<?php
  }
   else if($t_diff>=960 && $t_diff<1020)
  {
  	?>
  	<td><b><?php echo "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;".$name."<br>";?></b><h6 style="position: relative;left:18px;">16 Hours Ago</h6></td>
  	<?php
  }
   else if($t_diff>=1020 && $t_diff<1080)
  {
  	?>
  	<td><b><?php echo "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;".$name."<br>";?></b><h6 style="position: relative;left:18px;">17 Hours Ago</h6></td>
  	<?php
  }
   else if($t_diff>=1080 && $t_diff<1140)
  {
  	?>
  	<td><b><?php echo "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;".$name."<br>";?></b><h6 style="position: relative;left:18px;">18 Hours Ago</h6></td>
  	<?php
  }
   else if($t_diff>=1140 && $t_diff<1200)
  {
  	?>
  	<td><b><?php echo "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;".$name."<br>";?></b><h6 style="position: relative;left:18px;">19 Hours Ago</h6></td>
  	<?php
  }
  else if($t_diff>=1200 && $t_diff<1260)
  {
  	?>
  	<td><b><?php echo "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;".$name."<br>";?></b><h6 style="position: relative;left:18px;">20 Hours Ago</h6></td>
  	<?php
  }
  else if($t_diff>=1260 && $t_diff<1320)
  {
  	?>
  	<td><b><?php echo "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;".$name."<br>";?></b><h6 style="position: relative;left:18px;">21 Hours Ago</h6></td>
  	<?php
  }
  else if($t_diff>=1320 && $t_diff<1380)
  {
  	?>
  	<td><b><?php echo "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;".$name."<br>";?></b><h6 style="position: relative;left:18px;">22 Hours Ago</h6></td>
  	<?php
  }
  else if($t_diff>=1380 && $t_diff<1440)
  {
  	?>
  	<td><b><?php echo "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;".$name."<br>";?></b><h6 style="position: relative;left:18px;">23 Hours Ago</h6></td>
  	<?php
  }





  
  }
  else if($days<31){
  	?>
  	<td><b><?php echo "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;".$name."<br>"?></b><h6 style="position: relative;left:18px;"><?php echo $days."&nbsp";?>Days Ago</h6>	</td>
  	<?php
  }
  else if($days>=31 && $days<60){
  	?>
  	<td><b><?php echo "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;".$name."<br>";?></b><h6 style="position: relative;left:18px;">1 Month Ago</h6></td>
  	<?php

  }
   else if($days>=60 && $days<90){
  	?>
  	<td><b><?php echo "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;".$name."<br>";?></b><h6 style="position: relative;left:18px;">2 Month Ago</h6></td>
  	<?php

  }
  else if($days>=90 && $days<120){
  	?>
  	<td><b><?php echo "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;".$name."<br>";?></b><h6 style="position: relative;left:18px;">3 Month Ago</h6></td>
  	<?php

  }else if($days>=120 && $days<150){
  	?>
  	<td><b><?php echo "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;".$name."<br>";?></b><h6 style="position: relative;left:18px;">4 Month Ago</h6></td>
  	<?php

  }
  else if($days>=150 && $days<180){
  	?>
  	<td><b><?php echo "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;".$name."<br>";?></b><h6 style="position: relative;left:18px;">5 Month Ago</h6></td>
  	<?php

  }
  else if($days>=180 && $days<210){
  	?>
  	<td><b><?php echo "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;".$name."<br>";?></b><h6 style="position: relative;left:18px;">6 Month Ago</h6></td>
  	<?php

  }
  else if($days>=210 && $days<240){
  	?>
  	<td><b><?php echo "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;".$name."<br>";?></b><h6 style="position: relative;left:18px;">7 Month Ago</h6></td>
  	<?php

  }
  else if($days>=240 && $days<270){
  	?>
  	<td><b><?php echo "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;".$name."<br>";?></b><h6 style="position: relative;left:18px;">8 Month Ago</h6></td>
  	<?php

  }
  else if($days>=270 && $days<300){
  	?>
  	<td><b><?php echo "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;".$name."<br>";?></b><h6 style="position: relative;left:18px;">9 Month Ago</h6></td>
  	<?php

  }
  else if($days>=300 && $days<330){
  	?>
  	<td><b><?php echo "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;".$name."<br>";?></b><h6 style="position: relative;left:18px;">10 Month Ago</h6></td>
  	<?php

  }else if($days>=330 && $days<360){
  	?>
  	<td><b><?php echo "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;".$name."<br>";?></b><h6 style="position: relative;left:18px;">11 Month Ago</h6></td>
  	<?php

  }
  else if($days>=360 && $days<720){
  	?>
  	<td><b><?php echo "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;".$name."<br>";?></b><h6 style="position: relative;left:18px;">1 Year Ago</h6></td>
  	<?php

  }
  else if($days>=720){
  	?>
  	<td><b><?php echo "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;".$name."<br>";?></b><h6 style="position: relative;left:18px;">2 Year Ago</h6></td>
  	<?php
}
		
	?>
	 <?php  if ($sud!=0) 
			{
			 	$sql = mysqli_query($connection,"SELECT * FROM user_profile where id='$generated_by'");
				$arr=mysqli_fetch_array($sql);
				$g_name=$arr['name'];
				$mobile_no=$arr['mobile'];
			}
			else{
				$sql = mysqli_query($connection,"SELECT * FROM user where id='$generated_by'");
				$arr=mysqli_fetch_array($sql);
				$g_name=$arr['name'];
				$mobile_no=$arr['contact'];
			}
				 ?>
				 <td><b><br><?php echo "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;".$g_name."</br>";?></b><h6 style="position: relative;left:25px;"><?php echo $mobile_no;?></h6><h6 style="position: relative;left:24px;"><?php echo  $row6['sche_type'];?></h6></td>
				  
		
			
               <!--  <td><?php echo $row6['sche_type'];?></td> --> 
                 <td><?php echo $en_remark;?></td> 
                   <?php if($user_id==$generated_by)
                   {?>
                  <td><a href='dashboard.php?page=enquiry_plan&ed=<?php echo $student_id;?>&id=<?php echo $tab_id;?>'><span class="icon fa fa-edit"></span></a></td>
                  <?php 
                  } else
                  {
                  	?>
                  	<td><a><span class="icon fa fa-edit"></span></a></td>
                  	<?php
                  }?>

                	
		               
               
               
                
                
                
                

              
               
                
		
      
		</tr>
		
			<?php 
                        } }  
			?>
	</tbody>
	</table>
	</div>
	</div>
	<div id="myModal" class="modal fade" tabindex="1" role="dialog">
    <div class="modal-dialog modal-md">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h3 class="modal-title" align="center">Minutes of the Meeting</h3>
            </div>
            <div class="modal-body">    
                <form  method="post" id="myform1" enctype="multipart/formdata"> 
                    <input type="hidden" name="sub_us_ty" value="<?php echo $utype; ?>">
                <input type="hidden" name="log" id="log">
                 
                 <div class="row">
                    <div class="col-sm-2 col-md-2 col-lg-2"></div>
                    <div class="col-sm-8 col-md-8 col-lg-8"><h4>Description</h4><textarea class="form-control" name="remark_u" id="remark_u"></textarea></div>
                    <div class="col-sm-2 col-md-2 col-lg-2"></div>
                </div> 

                 <div class="row">
                    <div class="col-sm-2 col-md-2 col-lg-2"></div>
                    <div class="col-sm-8 col-md-8 col-lg-8"><h4>Document Upload:</h4><input type="file" name="file" id="file" class="form-control"><input type="text" name="doc" id="doc" style="border:none;width:300px;" ></div>
                    <div class="col-sm-2 col-md-2 col-lg-2"></div>
                </div> 

                
           
                <br>
              
	            <div class="modal-footer">
	               <button class="btn btn-primary submit" name="save1" id="btn_save1">Save</button>
	               <button type="button" class="btn btn-warning btn-md" data-dismiss="modal">Cancel</button>      
		        </div>

                </form>
            </div>
        </div>
    </div>
</div>
	
	
	
	<script>
	function efun(id)
{
    $.ajax({
             url:'get_remark_data.php',
             type:'POST',
             data:{
                    id:id
             },
	
             success: function(data)
             {
                var obj = $.parseJSON(data);
                $('#log').val(obj.id);
                $('#remark_u').val(obj.mom_description);
                $('#file').prop(obj.upload_document);
                $('#doc').val(obj.upload_document);
               
                if(data==1)
                {
                    alert("update");
                }

             } 

    });

}
	
	
	
	
    function selectChangeHandler(selectNode) {
         if (selectNode.selectedIndex == 5 || selectNode.selectedIndex == 3 || selectNode.selectedIndex == 4) {
             alert("This will Notify to Director");
         }
    }
</script>

<script>

$('form#myform1').submit(function(e){

     e.preventDefault();


	  		$("button#btn_save1").button('loading');
	         $.ajax({
						url:'update_remark.php',
						type:"POST",
						data: new FormData(this),
                                                contentType:false,
                                                processData:false,
						success: function(data)
						{
							$("button#btn_save1").button('reset');
							if(data==1)
							{
								// alert('Save Successfully !!!');
								
								//  window.location.href= "logproduct.php";
								  swal({
									  position: 'top-right',
	 							      type: 'success',
	  								  title: 'Save Successfully!!!',
	  								  showConfirmButton: false,
	  								  timer: 1500
								  })
								  window.setTimeout(function()
								    { 
 										window.location.href= "dashboard.php?page=enquiry_plan&ed=<?php echo $id;?>";
 								 	} ,1500);
								 
                                                                }else if(data==3)
                                                                {
								// alert('Save Successfully !!!');
								
								//  window.location.href= "logproduct.php";
								  swal({
									  position: 'top-right',
	 							      type: 'success',
	  								  title: 'Save Successfully!!!',
	  								  showConfirmButton: false,
	  								  timer: 1500
								  })
								  window.setTimeout(function()
								    { 
 										window.location.href= "dashboard.php?page=enquiry_plan&ed=<?php echo $id;?>";
 								 	} ,1500);
								 
							}
							else if(data==2)
							{
								alert('Error....');
								// $('#msg').html('Please Check Error.');
								// $('#msg').css('color','red');
								return false;
							} 
						}
				   });
	    		 
});

</script>
<script>

	function updateData(button)
	{
     var id=button.id;
    
     var status=$("#sche_type").val();
    
     var comment=$("#en_remark").val();
     
     $.ajax({
     	url:'update_log.php',
     	data:{'id':id,'status':status,'comment':comment},
     	type:'post',
     	dataType:'json',
     	success:function(response)
     	{
        if(response==1)
        {
        window.location.href= "dashboard.php?page=enquiry_plan&ed=<?php echo $id;?>";
        }
        else
        {

        }
     	}

     });
	}


	</script>

