<?php

include "config.php";

// $user_id=$_SESSION['login_user'];

 $fromdate=strtotime($_POST['fromDate']); 
 $fromdate=date("Y-m-d",$fromdate);
 $todate=strtotime($_POST['toDate']); 
 $todate=date("Y-m-d",$todate);
 $utype="admin";
   $user_id = $_POST['us_id'];
   $type = $_POST['type'];
  $type1 = $_POST['type1'];

?> 
<?php
if($type!='' && !empty($type) && empty($type1))
{
?>   
<div class="panel-body"></div>
<table id="example" class="datatable table table-striped">
  <thead>
    <tr>
    
          <th>Id</th>          
          <th>Date</th>
          <th>Student Name</th>          
          <th>Email Id</th>
          <th>Phone Number</th>    
          <th>Course List</th>
          <th>Fees</th>
          <th>Generated By</th>
          <th>Assign To</th>
      
  </thead>
  <tbody>

        <?php
			if($fromdate!='' && $todate!='')
				{
					$sr_no=0;
		          $sql1 =mysqli_query($connection,"SELECT * From student WHERE  date(cur_date) BETWEEN  '$fromdate' AND '$todate' AND user_id='$user_id'   and generated_by='$type' ORDER BY cur_date DESC ")or die(mysqli_error($connection));
		          
		           while($row=mysqli_fetch_array($sql1))
					{
					$c_id=$row['id'];
          $user_id=$row['user_id'];
          $sud=$row['sub_user_id'];
          $assign_to=$row['assign_to'];
                $generated_by=$row['generated_by'];
                $assign_to_name=$row['assign_to_name'];
    ?>
            <tr><td><?php echo $row['id'];?></td>
              <td><?php echo date('d-m-Y', strtotime($row['cur_date']));?></td>
                <td>
                <?php if ($utype=='admin'){?>
                <?php echo"<a href='dashboard.php?page=enquiry_plan&ed=".$row['id']."'>".$row['name']."</a>";?>
            <?php }
            else{ ?>
             <?php echo"<a href='dashboard.php?page=enquiry_plan&ed=".$row['id']."'>".$row['name']."</a>";?>
            <?php } ?>
                </td>
          <td><?php echo $row['email'];?></td>
          <td><?php echo $row['contact_no'];?></td>
          <td><?php echo $row['course_list'];?></td>
          <td><?php echo $row['course_fee'];?></td>
          
          
          <?php 
          if ($sud!=0 && $user_id!=0) 
      {
        $sql = mysqli_query($connection,"SELECT * FROM user_profile where id='$generated_by'");
        $arr=mysqli_fetch_array($sql);
        $g_name=$arr['name'];
      }
      else{
        $sql = mysqli_query($connection,"SELECT * FROM user where id='$generated_by'");
        $arr=mysqli_fetch_array($sql);
        $g_name=$arr['name'];
      }

          ?>
          
          
                <td><?php echo $g_name;?></td>
                  <td><?php echo $assign_to_name;?></td>
              
          
				</tr>
				<?php
					}
        }
			   ?>
			  </tbody>
			</table>
      <?php
    }
    else if($type!='' && !empty($type) && !empty($type1) && $type1!='')
    {
      ?>
<div class="panel-body"></div>
<table id="example" class="datatable table table-striped">
  <thead>
    <tr>
    
     <th>Student Name</th>
     <th>Log Generated By</th>
    
     <th>Comment</th>
     <th>Edit</th>
      
  </thead>
  <tbody>

        <?php
      if($fromdate!='' && $todate!='')
        {
          $sr_no=0;
              $sql12 =mysqli_query($connection,"SELECT * From generate_log WHERE  date(cur_date) BETWEEN  '$fromdate' AND '$todate' AND user_id='$user_id' and generated_by='$type' and sche_type='$type1'  ORDER BY cur_date DESC ")or die(mysqli_error($connection));         
               while($row=mysqli_fetch_array($sql12))
          {
        
            
    $tab_id=$row['id'];
    $cur_date=$row['cur_date'];
    $cur_time=$row['cur_time'];
    $sche_type=$row['sche_type'];
    $sche_date=$row['sche_date']; 
    //$sche_action=$row['sche_action'];   
    $sche_time=$row['sche_time'];
    //$en_call_type=$row['en_call_type']; 
    $en_status=$row['en_status'];
    $en_remark=$row['en_remark'];
    $dir_remark=$row['dir_remark'];
    $generated_by=$row['generated_by'];
      $sud=$row['sub_user_id']; 
      $student_id=$row['student_id'];
      $sql7=mysqli_query($connection,"select * from student where id='$student_id'");
      $name_sql=mysqli_fetch_array($sql7);
      $name=$name_sql['name'];

      
        $timestamp = strtotime($cur_date);
        $timestamp1= strtotime($sche_date);
        $date1=date('d-m-Y',$timestamp);
        $date2=date('d-m-Y',$timestamp1);
              
    $var5=mysqli_query($connection,"select * from admin_enquiry_status where enquiry_status_id='$en_status'");
    $row5=mysqli_fetch_array($var5);
    $var6=mysqli_query($connection,"select * from  mstr_schedule where id='$sche_type'");
    $row6=mysqli_fetch_array($var6);
  if(function_exists('date_default_timezone_set'))
          {
                         date_default_timezone_set("Asia/Kolkata");
              }
 $data21=date('Y-m-d');
 $data222=date('h:i:s');
 $diff=strtotime($data21)-strtotime($cur_date);
 $diff1=strtotime($data222)-strtotime($cur_time);
 $tdiff= abs($diff1)/(60);
 $t_diff=bcdiv($tdiff,1);
 $days=$diff/(86400);
  if($days==0)
  {
    if($t_diff<60)
    {
    ?>
    <td><b><?php echo "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;".$name."<br>";?></b><h6 style="position: relative;left:18px;"><?php echo $t_diff."&nbsp";?>Minutes Ago</h6></td>
    <?php
  }
  else if($t_diff>=60 && $t_diff<120)
  {
    ?>
    <td><b><?php echo "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;".$name."<br>";?></b><h6 style="position: relative;left:18px;">1 Hours Ago</h6></td>
    <?php
  }
  else if($t_diff>=120 && $t_diff<180)
  {
    ?>
    <td><b><?php echo "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;".$name."<br>";?></b><h6 style="position: relative;left:18px;">2 Hours Ago</h6></td>
    <?php
  }
  else if($t_diff>=180 && $t_diff<240)
  {
    ?>
    <td><b><?php echo "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;".$name."<br>";?></b><h6 style="position: relative;left:18px;">3 Hours Ago</h6></td>
    <?php
  }
  else if($t_diff>=240 && $t_diff<300)
  {
    ?>
    <td><b><?php echo "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;".$name."<br>";?></b><h6 style="position: relative;left:18px;">4 Hours Ago</h6></td>
    <?php
  }
  else if($t_diff>=300 && $t_diff<360)
  {
    ?>
    <td><b><?php echo "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;".$name."<br>";?></b><h6 style="position: relative;left:18px;">5 Hours Ago</h6></td>
    <?php
  }
  else if($t_diff>=360 && $t_diff<420)
  {
    ?>
    <td><b><?php echo "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;".$name."<br>";?></b><h6 style="position: relative;left:18px;">6 Hours Ago</h6></td>
    <?php
  }
  else if($t_diff>=420 && $t_diff<480)
  {
    ?>
    <td><b><?php echo "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;".$name."<br>";?></b><h6 style="position: relative;left:18px;">7 Hours Ago</h6></td>
    <?php
  }
   else if($t_diff>=480 && $t_diff<540)
  {
    ?>
    <td><b><?php echo "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;".$name."<br>";?></b><h6 style="position: relative;left:18px;">8 Hours Ago</h6></td>
    <?php
  }
  else if($t_diff>=540 && $t_diff<600)
  {
    ?>
    <td><b><?php echo "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;".$name."<br>";?></b><h6 style="position: relative;left:18px;">9 Hours Ago</h6></td>
    <?php
  }
  else if($t_diff>=600 && $t_diff<660)
  {
    ?>
    <td><b><?php echo "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;".$name."<br>";?></b><h6 style="position: relative;left:18px;">10 Hours Ago</h6></td>
    <?php
  }
   else if($t_diff>=660 && $t_diff<720)
  {
    ?>
    <td><b><?php echo "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;".$name."<br>";?></b><h6 style="position: relative;left:18px;">11 Hours Ago</h6></td>
    <?php
  }
   else if($t_diff>=720 && $t_diff<780)
  {
    ?>
    <td><b><?php echo "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;".$name."<br>";?></b><h6 style="position: relative;left:18px;">12 Hours Ago</h6></td>
    <?php
  }
   else if($t_diff>=780 && $t_diff<840)
  {
    ?>
    <td><b><?php echo "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;".$name."<br>";?></b><h6 style="position: relative;left:18px;">13 Hours Ago</h6></td>
    <?php
  }
   else if($t_diff>=840 && $t_diff<900)
  {
    ?>
    <td><b><?php echo "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;".$name."<br>";?></b><h6 style="position: relative;left:18px;">14 Hours Ago</h6></td>
    <?php
  }
   else if($t_diff>=900 && $t_diff<960)
  {
    ?>
    <td><b><?php echo "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;".$name."<br>";?></b><h6 style="position: relative;left:18px;">15 Hours Ago</h6></td>
    <?php
  }
   else if($t_diff>=960 && $t_diff<1020)
  {
    ?>
    <td><b><?php echo "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;".$name."<br>";?></b><h6 style="position: relative;left:18px;">16 Hours Ago</h6></td>
    <?php
  }
   else if($t_diff>=1020 && $t_diff<1080)
  {
    ?>
    <td><b><?php echo "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;".$name."<br>";?></b><h6 style="position: relative;left:18px;">17 Hours Ago</h6></td>
    <?php
  }
   else if($t_diff>=1080 && $t_diff<1140)
  {
    ?>
    <td><b><?php echo "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;".$name."<br>";?></b><h6 style="position: relative;left:18px;">18 Hours Ago</h6></td>
    <?php
  }
   else if($t_diff>=1140 && $t_diff<1200)
  {
    ?>
    <td><b><?php echo "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;".$name."<br>";?></b><h6 style="position: relative;left:18px;">19 Hours Ago</h6></td>
    <?php
  }
  else if($t_diff>=1200 && $t_diff<1260)
  {
    ?>
    <td><b><?php echo "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;".$name."<br>";?></b><h6 style="position: relative;left:18px;">20 Hours Ago</h6></td>
    <?php
  }
  else if($t_diff>=1260 && $t_diff<1320)
  {
    ?>
    <td><b><?php echo "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;".$name."<br>";?></b><h6 style="position: relative;left:18px;">21 Hours Ago</h6></td>
    <?php
  }
  else if($t_diff>=1320 && $t_diff<1380)
  {
    ?>
    <td><b><?php echo "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;".$name."<br>";?></b><h6 style="position: relative;left:18px;">22 Hours Ago</h6></td>
    <?php
  }
  else if($t_diff>=1380 && $t_diff<1440)
  {
    ?>
    <td><b><?php echo "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;".$name."<br>";?></b><h6 style="position: relative;left:18px;">23 Hours Ago</h6></td>
    <?php
  }

  }
  else if($days<31){
    ?>
    <td><b><?php echo "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;".$name."<br>"?></b><h6 style="position: relative;left:18px;"><?php echo $days."&nbsp";?>Days Ago</h6> </td>
    <?php

  }
  else if($days>=31 && $days<60){
    ?>
    <td><b><?php echo "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;".$name."<br>";?></b><h6 style="position: relative;left:18px;">1 Month Ago</h6></td>
    <?php

  }
   else if($days>=60 && $days<90){
    ?>
    <td><b><?php echo "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;".$name."<br>";?></b><h6 style="position: relative;left:18px;">2 Month Ago</h6></td>
    <?php

  }
  else if($days>=90 && $days<120){
    ?>
    <td><b><?php echo "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;".$name."<br>";?></b><h6 style="position: relative;left:18px;">3 Month Ago</h6></td>
    <?php

  }else if($days>=120 && $days<150){
    ?>
    <td><b><?php echo "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;".$name."<br>";?></b><h6 style="position: relative;left:18px;">4 Month Ago</h6></td>
    <?php

  }
  else if($days>=150 && $days<180){
    ?>
    <td><b><?php echo "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;".$name."<br>";?></b><h6 style="position: relative;left:18px;">5 Month Ago</h6></td>
    <?php

  }
  else if($days>=180 && $days<210){
    ?>
    <td><b><?php echo "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;".$name."<br>";?></b><h6 style="position: relative;left:18px;">6 Month Ago</h6></td>
    <?php

  }
  else if($days>=210 && $days<240){
    ?>
    <td><b><?php echo "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;".$name."<br>";?></b><h6 style="position: relative;left:18px;">7 Month Ago</h6></td>
    <?php

  }
  else if($days>=240 && $days<270){
    ?>
    <td><b><?php echo "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;".$name."<br>";?></b><h6 style="position: relative;left:18px;">8 Month Ago</h6></td>
    <?php

  }
  else if($days>=270 && $days<300){
    ?>
    <td><b><?php echo "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;".$name."<br>";?></b><h6 style="position: relative;left:18px;">9 Month Ago</h6></td>
    <?php

  }
  else if($days>=300 && $days<330){
    ?>
    <td><b><?php echo "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;".$name."<br>";?></b><h6 style="position: relative;left:18px;">10 Month Ago</h6></td>
    <?php

  }else if($days>=330 && $days<360){
    ?>
    <td><b><?php echo "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;".$name."<br>";?></b><h6 style="position: relative;left:18px;">11 Month Ago</h6></td>
    <?php

  }
  else if($days>=360 && $days<720){
    ?>
    <td><b><?php echo "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;".$name."<br>";?></b><h6 style="position: relative;left:18px;">1 Year Ago</h6></td>
    <?php

  }
  else if($days>=720){
    ?>
    <td><b><?php echo "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;".$name."<br>";?></b><h6 style="position: relative;left:18px;">2 Year Ago</h6></td>
    <?php
}
    
  ?>
   <?php  if ($sud!=0) 
      {
        $sql = mysqli_query($connection,"SELECT * FROM user_profile where id='$generated_by'");
        $arr=mysqli_fetch_array($sql);
        $g_name=$arr['name'];
        $mobile_no=$arr['mobile'];
      }
      else{
        $sql = mysqli_query($connection,"SELECT * FROM user where id='$generated_by'");
        $arr=mysqli_fetch_array($sql);
        $g_name=$arr['name'];
        $mobile_no=$arr['mobile'];
      }
         ?>
         <td><b><?php echo "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;".$g_name."<br>";?></b><h6 style="position: relative;left:25px;"><?php echo $mobile_no;?></h6><h6 style="position: relative;left:30px;"><?php echo  $row6['sche_type'];?></h6></td>
          
    
      
               
                 <td><?php echo $en_remark;?></td>
                 <?php if($user_id==$generated_by)
                   {?>
                  <td><a href='dashboard.php?page=enquiry_plan&ed=<?php echo $student_id;?>&id=<?php echo $tab_id;?>'><span class="icon fa fa-edit"></span></a></td>
                  <?php 
                  } else
                  {
                    ?>
                    <td><a><span class="icon fa fa-edit"></span></a></td>
                    <?php
                  }?> </tr>
                 <?php
               }
               }
                 ?>
        </tbody>
      </table>
      <?php
    
 
  }
  ?>
